import type { ChartConfiguration, SupportedChartType } from "@/types";

function escapeHTML(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function generateHTML(
  chartType: SupportedChartType,
  chartConfig: ChartConfiguration,
  summary: string,
  title: string,
  csvText?: string,
  totalRows?: number,
): string {
  const escapedSummary = escapeHTML(summary);
  const escapedTitle = escapeHTML(title);
  // Escape < in JSON to prevent </script> from breaking the script block
  const configJSON = JSON.stringify(chartConfig).replace(/</g, "\\u003c");
  // Sanitize chartType to only allow alphanumeric characters
  const safeChartType = chartType.replace(/[^a-zA-Z]/g, "");

  let csvSection = "";
  if (csvText && totalRows !== undefined) {
    const lines = csvText.split("\n").filter((line) => line.trim() !== "");
    const headers = lines.length > 0 ? lines[0].split(",") : [];
    const dataLines = lines.slice(1);
    const previewRows = dataLines.slice(0, 10);
    const previewCount = Math.min(previewRows.length, 10);
    const encodedCsv = encodeURIComponent(csvText);

    const headerCells = headers
      .map((h) => `<th>${escapeHTML(h.trim())}</th>`)
      .join("");
    const bodyRows = previewRows
      .map((row) => {
        const cells = row.split(",")
          .map((cell) => `<td>${escapeHTML(cell.trim())}</td>`)
          .join("");
        return `<tr>${cells}</tr>`;
      })
      .join("\n          ");

    csvSection = `
  <details class="source-data">
    <summary>Source Data &mdash; ${previewCount} of ${totalRows} rows shown</summary>
    <div class="source-data-content">
      <table>
        <thead><tr>${headerCells}</tr></thead>
        <tbody>
          ${bodyRows}
        </tbody>
      </table>
      <a href="data:text/csv;charset=utf-8,${encodedCsv}" download="source-data.csv" class="csv-download">Download full CSV</a>
    </div>
  </details>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapedTitle}</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
      color: #000;
      background: #fff;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header { border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; margin-bottom: 2rem; }
    h1 { font-size: 1.5rem; font-weight: 700; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
    .card { border: 1px solid #e5e7eb; border-radius: 0.5rem; padding: 1.5rem; }
    .card h2 { font-size: 1.125rem; font-weight: 600; margin-bottom: 1rem; }
    .summary { font-size: 0.875rem; line-height: 1.625; color: #374151; white-space: pre-wrap; }
    .chart-container { position: relative; height: 320px; }
    footer { border-top: 1px solid #e5e7eb; margin-top: 2rem; padding-top: 1rem; text-align: center; font-size: 0.75rem; color: #9ca3af; }
    .source-data { border: 1px solid #e5e7eb; border-radius: 0.5rem; margin-top: 1.5rem; }
    .source-data summary { cursor: pointer; padding: 1rem 1.5rem; font-weight: 600; font-size: 0.875rem; color: #374151; }
    .source-data-content { padding: 0 1.5rem 1.5rem; }
    .source-data table { width: 100%; border-collapse: collapse; font-size: 0.75rem; margin-bottom: 1rem; }
    .source-data th, .source-data td { border: 1px solid #e5e7eb; padding: 0.375rem 0.75rem; text-align: left; }
    .source-data th { background: #f9fafb; font-weight: 600; }
    .csv-download { display: inline-block; font-size: 0.75rem; color: #2563eb; text-decoration: underline; }
  </style>
</head>
<body>
  <header><h1>${escapedTitle}</h1></header>
  <div class="grid">
    <div class="card">
      <h2>Chart</h2>
      <div class="chart-container">
        <canvas id="chart"></canvas>
      </div>
    </div>
    <div class="card">
      <h2>Executive Summary</h2>
      <div class="summary">${escapedSummary}</div>
    </div>
  </div>${csvSection}
  <footer>Generated by Prism</footer>
  <script>
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {
      type: '${safeChartType}',
      data: ${configJSON},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { tooltip: { enabled: true } }
      }
    });
  </script>
</body>
</html>`;
}
