import type { ChartConfiguration, SupportedChartType } from "@/types";

function escapeHTML(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function generateHTML(
  chartType: SupportedChartType,
  chartConfig: ChartConfiguration,
  summary: string,
): string {
  const escapedSummary = escapeHTML(summary);
  const configJSON = JSON.stringify(chartConfig);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prism Report</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
      color: #000;
      background: #fff;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header { border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; margin-bottom: 2rem; }
    h1 { font-size: 1.5rem; font-weight: 700; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
    .card { border: 1px solid #e5e7eb; border-radius: 0.5rem; padding: 1.5rem; }
    .card h2 { font-size: 1.125rem; font-weight: 600; margin-bottom: 1rem; }
    .summary { font-size: 0.875rem; line-height: 1.625; color: #374151; white-space: pre-wrap; }
    .chart-container { position: relative; height: 320px; }
    footer { border-top: 1px solid #e5e7eb; margin-top: 2rem; padding-top: 1rem; text-align: center; font-size: 0.75rem; color: #9ca3af; }
  </style>
</head>
<body>
  <header><h1>Prism Report</h1></header>
  <div class="grid">
    <div class="card">
      <h2>Chart</h2>
      <div class="chart-container">
        <canvas id="chart"></canvas>
      </div>
    </div>
    <div class="card">
      <h2>Executive Summary</h2>
      <div class="summary">${escapedSummary}</div>
    </div>
  </div>
  <footer>Generated by Prism</footer>
  <script>
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {
      type: '${chartType}',
      data: ${configJSON},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { tooltip: { enabled: true } }
      }
    });
  </script>
</body>
</html>`;
}
