/// <reference lib="deno.ns" />
import { assertEquals, assertStringIncludes } from "@std/assert";

// Inline implementation for Deno tests
function escapeHTML(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

type SupportedChartType =
  | "bar"
  | "line"
  | "pie"
  | "doughnut"
  | "polarArea"
  | "radar";

interface ChartConfiguration {
  labels: string[];
  datasets: {
    label: string;
    data: number[];
    backgroundColor?: string | string[];
    borderColor?: string | string[];
    borderWidth?: number;
  }[];
}

function generateHTML(
  chartType: SupportedChartType,
  chartConfig: ChartConfiguration,
  summary: string,
  title: string,
  csvText?: string,
  totalRows?: number,
): string {
  const escapedSummary = escapeHTML(summary);
  const escapedTitle = escapeHTML(title);
  const configJSON = JSON.stringify(chartConfig).replace(/</g, "\\u003c");
  const safeChartType = chartType.replace(/[^a-zA-Z]/g, "");

  let csvSection = "";
  if (csvText && totalRows !== undefined) {
    const lines = csvText.split("\n").filter((line) => line.trim() !== "");
    const headers = lines.length > 0 ? lines[0].split(",") : [];
    const dataLines = lines.slice(1);
    const previewRows = dataLines.slice(0, 10);
    const previewCount = Math.min(previewRows.length, 10);
    const encodedCsv = encodeURIComponent(csvText);

    const headerCells = headers
      .map((h) => `<th>${escapeHTML(h.trim())}</th>`)
      .join("");
    const bodyRows = previewRows
      .map((row) => {
        const cells = row.split(",")
          .map((cell) => `<td>${escapeHTML(cell.trim())}</td>`)
          .join("");
        return `<tr>${cells}</tr>`;
      })
      .join("\n          ");

    csvSection = `
  <details class="source-data">
    <summary>Source Data &mdash; ${previewCount} of ${totalRows} rows shown</summary>
    <div class="source-data-content">
      <table>
        <thead><tr>${headerCells}</tr></thead>
        <tbody>
          ${bodyRows}
        </tbody>
      </table>
      <a href="data:text/csv;charset=utf-8,${encodedCsv}" download="source-data.csv" class="csv-download">Download full CSV</a>
    </div>
  </details>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapedTitle}</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
      color: #000;
      background: #fff;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header { border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; margin-bottom: 2rem; }
    h1 { font-size: 1.5rem; font-weight: 700; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
    .card { border: 1px solid #e5e7eb; border-radius: 0.5rem; padding: 1.5rem; }
    .card h2 { font-size: 1.125rem; font-weight: 600; margin-bottom: 1rem; }
    .summary { font-size: 0.875rem; line-height: 1.625; color: #374151; white-space: pre-wrap; }
    .chart-container { position: relative; height: 320px; }
    footer { border-top: 1px solid #e5e7eb; margin-top: 2rem; padding-top: 1rem; text-align: center; font-size: 0.75rem; color: #9ca3af; }
    .source-data { border: 1px solid #e5e7eb; border-radius: 0.5rem; margin-top: 1.5rem; }
    .source-data summary { cursor: pointer; padding: 1rem 1.5rem; font-weight: 600; font-size: 0.875rem; color: #374151; }
    .source-data-content { padding: 0 1.5rem 1.5rem; }
    .source-data table { width: 100%; border-collapse: collapse; font-size: 0.75rem; margin-bottom: 1rem; }
    .source-data th, .source-data td { border: 1px solid #e5e7eb; padding: 0.375rem 0.75rem; text-align: left; }
    .source-data th { background: #f9fafb; font-weight: 600; }
    .csv-download { display: inline-block; font-size: 0.75rem; color: #2563eb; text-decoration: underline; }
  </style>
</head>
<body>
  <header><h1>${escapedTitle}</h1></header>
  <div class="grid">
    <div class="card">
      <h2>Chart</h2>
      <div class="chart-container">
        <canvas id="chart"></canvas>
      </div>
    </div>
    <div class="card">
      <h2>Executive Summary</h2>
      <div class="summary">${escapedSummary}</div>
    </div>
  </div>${csvSection}
  <footer>Generated by Prism</footer>
  <script>
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {
      type: '${safeChartType}',
      data: ${configJSON},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { tooltip: { enabled: true } }
      }
    });
  </script>
</body>
</html>`;
}

const sampleConfig: ChartConfiguration = {
  labels: ["A", "B"],
  datasets: [{ label: "Test", data: [10, 20], borderWidth: 1 }],
};

Deno.test("generates valid HTML document", () => {
  const html = generateHTML("bar", sampleConfig, "Test summary", "My Report");
  assertStringIncludes(html, "<!DOCTYPE html>");
  assertStringIncludes(html, "My Report");
});

Deno.test("includes Chart.js CDN", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report");
  assertStringIncludes(html, "cdn.jsdelivr.net/npm/chart.js@4");
});

Deno.test("includes chart type in config", () => {
  const html = generateHTML("pie", sampleConfig, "Summary", "Report");
  assertStringIncludes(html, "type: 'pie'");
});

Deno.test("includes chart data", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report");
  assertStringIncludes(html, '"labels":["A","B"]');
  assertStringIncludes(html, '"data":[10,20]');
});

Deno.test("escapes HTML in summary", () => {
  const html = generateHTML(
    "bar",
    sampleConfig,
    '<script>alert("xss")</script>',
    "Report",
  );
  assertStringIncludes(html, "&lt;script&gt;");
  assertEquals(html.includes('<script>alert("xss")</script>'), false);
});

Deno.test("includes Prism branding", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report");
  assertStringIncludes(html, "Generated by Prism");
});

Deno.test("escapes quotes in summary", () => {
  const html = generateHTML(
    "bar",
    sampleConfig,
    'He said "hello" & goodbye',
    "Report",
  );
  assertStringIncludes(html, "&quot;hello&quot;");
  assertStringIncludes(html, "&amp;");
});

// Security tests

Deno.test("chartType injection is sanitized", () => {
  // deno-lint-ignore no-explicit-any
  const injected = "bar'; alert(1); //" as any;
  const html = generateHTML(injected, sampleConfig, "Safe", "Report");
  assertEquals(html.includes("alert(1)"), false);
  assertStringIncludes(html, "type: 'baralert");
});

Deno.test("script-closing tag in labels does not break script block", () => {
  const maliciousConfig: ChartConfiguration = {
    labels: ['</script><script>alert("xss")</script>'],
    datasets: [{ label: "Test", data: [1], borderWidth: 1 }],
  };
  const html = generateHTML("bar", maliciousConfig, "Safe summary", "Report");
  // The raw </script> should not appear inside the data JSON
  const dataStart = html.indexOf("data: {");
  const scriptEnd = html.indexOf("</script>", dataStart);
  const dataSection = html.slice(dataStart, scriptEnd);
  assertEquals(dataSection.includes("</script>"), false);
  assertStringIncludes(html, "\\u003c");
});

Deno.test("empty labels array produces valid output", () => {
  const config: ChartConfiguration = {
    labels: [],
    datasets: [{ label: "Test", data: [], borderWidth: 1 }],
  };
  const html = generateHTML("bar", config, "Summary", "Report");
  assertStringIncludes(html, "<!DOCTYPE html>");
});

Deno.test("empty datasets array produces valid output", () => {
  const config: ChartConfiguration = {
    labels: ["A"],
    datasets: [],
  };
  const html = generateHTML("bar", config, "Summary", "Report");
  assertStringIncludes(html, "<!DOCTYPE html>");
});

Deno.test("all 6 chart types produce valid output", () => {
  const types: SupportedChartType[] = [
    "bar",
    "line",
    "pie",
    "doughnut",
    "polarArea",
    "radar",
  ];
  for (const t of types) {
    const html = generateHTML(t, sampleConfig, "Summary", "Report");
    assertStringIncludes(html, `type: '${t}'`);
  }
});

Deno.test("empty string summary produces valid HTML", () => {
  const html = generateHTML("bar", sampleConfig, "", "Report");
  assertStringIncludes(html, "<!DOCTYPE html>");
  assertStringIncludes(html, '<div class="summary"></div>');
});

Deno.test("backtick in summary does not break template", () => {
  const html = generateHTML("bar", sampleConfig, "Value is `42`", "Report");
  assertStringIncludes(html, "Value is `42`");
});

Deno.test("title appears in <title> tag and <h1>", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Sales Overview 2024");
  assertStringIncludes(html, "<title>Sales Overview 2024</title>");
  assertStringIncludes(html, "<h1>Sales Overview 2024</h1>");
});

Deno.test("escapes HTML in title", () => {
  const html = generateHTML(
    "bar",
    sampleConfig,
    "Summary",
    '<script>alert(1)</script>',
  );
  assertStringIncludes(html, "&lt;script&gt;");
  assertEquals(html.includes('<script>alert(1)</script>'), false);
});

// CSV embedding tests

const sampleCsv = "Name,Age,City\nAlice,30,London\nBob,25,Paris\nCarol,35,Berlin";

Deno.test("includes collapsed details section when csvText provided", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 3);
  assertStringIncludes(html, "<details class");
  // Must NOT have the open attribute — collapsed by default
  assertEquals(html.includes("<details open"), false);
  assertStringIncludes(html, "</details>");
});

Deno.test("summary shows correct row count label", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 847);
  assertStringIncludes(html, "3 of 847 rows shown");
});

Deno.test("preview table includes headers as th elements", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 3);
  assertStringIncludes(html, "<th>Name</th>");
  assertStringIncludes(html, "<th>Age</th>");
  assertStringIncludes(html, "<th>City</th>");
});

Deno.test("preview table includes data rows", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 3);
  assertStringIncludes(html, "<td>Alice</td>");
  assertStringIncludes(html, "<td>30</td>");
  assertStringIncludes(html, "<td>London</td>");
  assertStringIncludes(html, "<td>Bob</td>");
});

Deno.test("preview table limited to first 10 rows", () => {
  const rows = Array.from({ length: 15 }, (_, i) => `Name${i},${i},City${i}`);
  const csv = "Name,Num,City\n" + rows.join("\n");
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", csv, 15);
  // Row 10 (index 9) should appear
  assertStringIncludes(html, "<td>Name9</td>");
  // Row 11 (index 10) should NOT appear
  assertEquals(html.includes("<td>Name10</td>"), false);
  // Summary should say 10 of 15
  assertStringIncludes(html, "10 of 15 rows shown");
});

Deno.test("includes data URI download link", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 3);
  assertStringIncludes(html, "data:text/csv;charset=utf-8,");
  assertStringIncludes(html, 'download="source-data.csv"');
  assertStringIncludes(html, "Download full CSV");
});

Deno.test("download link contains encoded CSV", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", sampleCsv, 3);
  const encoded = encodeURIComponent(sampleCsv);
  assertStringIncludes(html, encoded);
});

Deno.test("escapes HTML in CSV headers and cells", () => {
  const maliciousCsv = '<script>alert("h")</script>,Normal\n<img onerror=alert(1)>,Safe';
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", maliciousCsv, 1);
  assertStringIncludes(html, "&lt;script&gt;");
  assertStringIncludes(html, "&lt;img onerror=alert(1)&gt;");
  // Raw tags must not appear inside the table
  assertEquals(html.includes("<th><script>"), false);
  assertEquals(html.includes("<td><img"), false);
});

Deno.test("no details section when csvText is omitted", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report");
  assertEquals(html.includes("<details"), false);
});

Deno.test("no details section when csvText is empty string", () => {
  const html = generateHTML("bar", sampleConfig, "Summary", "Report", "", 0);
  assertEquals(html.includes("<details"), false);
});
