/// <reference lib="deno.ns" />
import { assertEquals, assertStringIncludes } from "@std/assert";

// Inline implementation for Deno tests
function escapeHTML(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

type SupportedChartType =
  | "bar"
  | "line"
  | "pie"
  | "doughnut"
  | "polarArea"
  | "radar";

interface ChartConfiguration {
  labels: string[];
  datasets: {
    label: string;
    data: number[];
    backgroundColor?: string | string[];
    borderColor?: string | string[];
    borderWidth?: number;
  }[];
}

function generateHTML(
  chartType: SupportedChartType,
  chartConfig: ChartConfiguration,
  summary: string,
): string {
  const escapedSummary = escapeHTML(summary);
  const configJSON = JSON.stringify(chartConfig).replace(/</g, "\\u003c");
  const safeChartType = chartType.replace(/[^a-zA-Z]/g, "");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prism Report</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
      color: #000;
      background: #fff;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header { border-bottom: 1px solid #e5e7eb; padding-bottom: 1rem; margin-bottom: 2rem; }
    h1 { font-size: 1.5rem; font-weight: 700; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
    .card { border: 1px solid #e5e7eb; border-radius: 0.5rem; padding: 1.5rem; }
    .card h2 { font-size: 1.125rem; font-weight: 600; margin-bottom: 1rem; }
    .summary { font-size: 0.875rem; line-height: 1.625; color: #374151; white-space: pre-wrap; }
    .chart-container { position: relative; height: 320px; }
    footer { border-top: 1px solid #e5e7eb; margin-top: 2rem; padding-top: 1rem; text-align: center; font-size: 0.75rem; color: #9ca3af; }
  </style>
</head>
<body>
  <header><h1>Prism Report</h1></header>
  <div class="grid">
    <div class="card">
      <h2>Chart</h2>
      <div class="chart-container">
        <canvas id="chart"></canvas>
      </div>
    </div>
    <div class="card">
      <h2>Executive Summary</h2>
      <div class="summary">${escapedSummary}</div>
    </div>
  </div>
  <footer>Generated by Prism</footer>
  <script>
    const ctx = document.getElementById('chart').getContext('2d');
    new Chart(ctx, {
      type: '${safeChartType}',
      data: ${configJSON},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { tooltip: { enabled: true } }
      }
    });
  </script>
</body>
</html>`;
}

const sampleConfig: ChartConfiguration = {
  labels: ["A", "B"],
  datasets: [{ label: "Test", data: [10, 20], borderWidth: 1 }],
};

Deno.test("generates valid HTML document", () => {
  const html = generateHTML("bar", sampleConfig, "Test summary");
  assertStringIncludes(html, "<!DOCTYPE html>");
  assertStringIncludes(html, "Prism Report");
});

Deno.test("includes Chart.js CDN", () => {
  const html = generateHTML("bar", sampleConfig, "Summary");
  assertStringIncludes(html, "cdn.jsdelivr.net/npm/chart.js@4");
});

Deno.test("includes chart type in config", () => {
  const html = generateHTML("pie", sampleConfig, "Summary");
  assertStringIncludes(html, "type: 'pie'");
});

Deno.test("includes chart data", () => {
  const html = generateHTML("bar", sampleConfig, "Summary");
  assertStringIncludes(html, '"labels":["A","B"]');
  assertStringIncludes(html, '"data":[10,20]');
});

Deno.test("escapes HTML in summary", () => {
  const html = generateHTML(
    "bar",
    sampleConfig,
    '<script>alert("xss")</script>',
  );
  assertStringIncludes(html, "&lt;script&gt;");
  assertEquals(html.includes('<script>alert("xss")</script>'), false);
});

Deno.test("includes Prism branding", () => {
  const html = generateHTML("bar", sampleConfig, "Summary");
  assertStringIncludes(html, "Generated by Prism");
});

Deno.test("escapes quotes in summary", () => {
  const html = generateHTML("bar", sampleConfig, 'He said "hello" & goodbye');
  assertStringIncludes(html, "&quot;hello&quot;");
  assertStringIncludes(html, "&amp;");
});

// Security tests

Deno.test("chartType injection is sanitized", () => {
  // deno-lint-ignore no-explicit-any
  const html = generateHTML("bar'; alert(1); //" as any, sampleConfig, "Safe");
  assertEquals(html.includes("alert(1)"), false);
  assertStringIncludes(html, "type: 'baralert");
});

Deno.test("script-closing tag in labels does not break script block", () => {
  const maliciousConfig: ChartConfiguration = {
    labels: ['</script><script>alert("xss")</script>'],
    datasets: [{ label: "Test", data: [1], borderWidth: 1 }],
  };
  const html = generateHTML("bar", maliciousConfig, "Safe summary");
  // The raw </script> should not appear inside the data JSON
  const dataStart = html.indexOf("data: {");
  const scriptEnd = html.indexOf("</script>", dataStart);
  const dataSection = html.slice(dataStart, scriptEnd);
  assertEquals(dataSection.includes("</script>"), false);
  assertStringIncludes(html, "\\u003c");
});

Deno.test("empty labels array produces valid output", () => {
  const config: ChartConfiguration = {
    labels: [],
    datasets: [{ label: "Test", data: [], borderWidth: 1 }],
  };
  const html = generateHTML("bar", config, "Summary");
  assertStringIncludes(html, "<!DOCTYPE html>");
});

Deno.test("empty datasets array produces valid output", () => {
  const config: ChartConfiguration = {
    labels: ["A"],
    datasets: [],
  };
  const html = generateHTML("bar", config, "Summary");
  assertStringIncludes(html, "<!DOCTYPE html>");
});

Deno.test("all 6 chart types produce valid output", () => {
  const types: SupportedChartType[] = [
    "bar",
    "line",
    "pie",
    "doughnut",
    "polarArea",
    "radar",
  ];
  for (const t of types) {
    const html = generateHTML(t, sampleConfig, "Summary");
    assertStringIncludes(html, `type: '${t}'`);
  }
});

Deno.test("empty string summary produces valid HTML", () => {
  const html = generateHTML("bar", sampleConfig, "");
  assertStringIncludes(html, "<!DOCTYPE html>");
  assertStringIncludes(html, '<div class="summary"></div>');
});

Deno.test("backtick in summary does not break template", () => {
  const html = generateHTML("bar", sampleConfig, "Value is `42`");
  assertStringIncludes(html, "Value is `42`");
});
